### ISSUE TITLE
INC9371045: Cirrus,Update member group population description

### ISSUE THREAD

**Issue by syawin** [syawin/optum#1]
# Tasks
## 11/15/2018
- [x] reach out to TJ to see if this group is part of other groups that need updating.
- [x] check if action is possible via UI. _it isn't_
- [x] write script.
- [x] test in local.
## 11/16/2018
- [x] test in zulu.
- [x] check if we should version/activate CO w/ kyle.
## 11/19/2018
- [x] submit to PDUT for approval.
- [x] confirm with customer that they have made the updates required on their end.
